config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'admin/users', sessions: 'users/sessions' }
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'resume' => 'resume#index'
  get 'resume_print' => 'resume#show'


  namespace :admin do
  get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
  get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories
  resources :portfolios do
    resources :portfolio_chunks
  end
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :categories, :users, :sessions
    resources :portfolios do
      resources :portfolio_chunks
    end
    resources :posts do
      resources :comments
      resources :post_chunks
    end
  end

  resources :posts do
    resources :comments
  end

  root 'dashboard#index'

  post 'wysiwygs', to: "admin/wysiwyg#create"
  get 'wysiwygs', to: "admin/wysiwyg#index"
  delete 'wysiwyg/:id', to: "admin/wysiwyg#destroy"
end

app/models/category.rb
class Category < ActiveRecord::Base
	extend PagedSearchable

	has_many :posts

	validates :name, presence: true

	def self.search(quote)
		where("name like ?", "%#{query}%")
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	attr_accessor :user_name

	validate :no_robots
	validates_presence_of :name, :body
	validates_email_format_of :email, :message => 'please enter a valid email'

	def sub_comments
	  Comment.where(reply_comment: id)
	end

	def no_robots
		if user_name!='name'
			errors.add(:base, "please don't change any hidden fields")
		end
	end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged
	has_many :portfolio_chunks

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	enum publish: [:not_published, :is_published]

  def visible?
		return true if is_published?
	end

	def self.sorted_public
		visible.priority
	end

	def self.visible
		Portfolio.where(id: (select { |p| p.visible? }).map(&:id))
	end

	def self.priority
		order('priority','created_at DESC')
	end
end

app/models/portfolio_chunk.rb
class PortfolioChunk < ActiveRecord::Base
	belongs_to :portfolio

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	extend PagedSearchable

  friendly_id :title, use: :slugged
	belongs_to :category
	belongs_to :user
	has_many :wysiwygs
	has_many :comments
	has_many :post_chunks

	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image,	storage: :s3

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search(query)
		where("title like ? OR body like?", "%#{query}%","%#{query}%")
	end

	enum state: [:draft, :production]

  def visible?
		return false unless production?
		return true if publish_date.blank?
		return true if publish_date < Time.zone.now
		false
	end

	def self.public(page)
		visible.pub_sorted.paginate(:per_page => 10, :page => page)
	end

	def self.visible
		Post.where(id: (select { |p| p.visible? }).map(&:id))
	end

	def self.pub_sorted
		order('job_priority','publish_date DESC NULLS LAST','created_at DESC')
	end

	def visible_published_date
		return publish_date unless publish_date.blank?
		created_at.to_time
	end

	def root_comments
		comments.where(reply_comment: nil)
	end
end

app/models/post_chunk.rb
class PostChunk < ActiveRecord::Base
	belongs_to :post

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  extend PagedSearchable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true, on: :create
	validates :password, confirmation: true, on: :create

	def self.search(query)
		where("name like ? OR email like?", "%#{query}%","%#{query}%")
	end
end

app/models/wysiwyg.rb
class Wysiwyg < ActiveRecord::Base
  belongs_to :post
  mount_uploader :image, ImageUploader

  attr_accessor :filename
end

app/controllers/comments_controller.rb
class CommentsController < PostsController
  def create
    comment = post.comments.create(comment_params)
    if comment.valid? && comment.save
      flash[:notice] = 'Comment Added'
      session.delete(:comment)
      redirect_to post_path(post, anchor: 'comment')
    else
      session[:comment] = comment
      flash[:alert] = Array(comment.errors).to_sentence
      redirect_to new_post_comment_path(post, comment_id: params["comment"]["reply_comment"], anchor: 'comment')
    end
  end

  private

  def comment_params
  	params.require(:comment).permit(:name, :email, :body, :post_id, :reply_comment, :user_name)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  caches_page :index
  expose(:portfolios) { Portfolio.all }
  expose(:portfolios_presenter) { PortfoliosDecorator.decorate(portfolios.sorted_public.first(9)) }
  expose(:posts) { Post.public(params[:page]).limit(4) }
  expose(:posts_presenter) { PostsDecorator.decorate(posts) }
  expose :portfolio
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  caches_page :show, :index
  expose :post, find_by: :slug
  expose(:post_presenter) { post.decorate }
  expose(:posts_presenter) { PostsDecorator.decorate(posts_filter) }
  expose(:limited_posts) { Post.public(params[:page]).limit(4) }
  expose(:limited_posts_presenter) { PostsDecorator.decorate(limited_posts) }
  expose(:user) { post.user }

  private

  def posts_filter
    params[:search] ? Post.search(params[:search]).public(params[:page]) : Post.public(params[:page])
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  caches_page :index, :show
  layout "plain", only: 'show'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment_descriptor
    if params[:comment_id].present?
      raw ("Replying to comment #{Comment.find(params[:comment_id]).try(:name)}<span class='comment_date'>#{Comment.find(params[:comment_id]).try(:created_at).to_time.strftime('%B %e %Y at %l:%M %p')}</span>")
    else
      "Add Comment"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wysiwyg_helper.rb
module WysiwygHelper
end

app/views/dashboard/_portfolio.html.erb
<div class="col-md-6 col-lg-4 col-xs-12 no-padding">
  <div class="white-background no-a-underline">
    <a href=<%= "#{portfolios_path(project_id: portfolio_counter + j*3)}#main" %>>
      <div class="set-background" style="background-image: url(<%= portfolio.image.url(:medium) %>)">
        <div class="hidden-text">
          <h1 class="center black shadow"><%= portfolio.name %></h1>
          <div class="center pb1">
            <%= render partial: 'tech_description', collection: portfolio.technology_description, as: :tech %>
          </div>
        </div>
      </div>
    </a>


  </div>
</div>

app/views/dashboard/_portfolio_slice.html.erb
<div class="no-padding">
  <%= render partial: 'portfolio', collection: slice, as: :portfolio, locals: { j: slice_counter } %>
</div>

app/views/dashboard/_tech_description.html.erb
<span class="technology"><%= tech %></span>

app/views/dashboard/index.html.erb
<div class="about">
  <% @title = "Jonathan Weyermann" %>
  <div class=''>
    <div role="main" class="group dashboard_header">
      <div class="col-sm-3 center">
          <%= image_tag "cartoon6.png", class: 'full-width' %>
      </div>
      <div class="col-sm-9 white center-xs">
        Hello, I'm 
        <h1 class="mt-0 display-4 font-weight-bold"><span class="">Jonathan Weyermann,</span></h1>
        <h1 class="mt-0 display-4 font-weight-bold"><span class="">web developer</span></h1>

        <h3 class="bio mt-3">
          I'm a seasoned full-stack developer with seven years of professional experience specializing in the design and implementation of complex, scalable web applications. I also share insights on web and personal development through my blog. Feel free to explore my <a href="#work">Work</a> and <%= link_to 'Resume', resume_path %> for more details.
        </h3>
      </div>
    </div>
  </div>
</div>



  <%= portfolios_presenter.visible_portfolios %>
  <div class="center mt2" id="work">
    <%= link_to 'View all Projects', portfolios_path, class: 'btn btn-primary rounded btn-lg center mt2' %>
  </div>


<div class="sidebar container">

  <div class="flex">
    <h1 class="flex1">Latest blog posts</h1>
    <h1 class="flex2"><hr /></h1>
  </div>
  <%= posts_presenter.visible_posts %>
  <div class="center">
    <%= link_to 'View all Posts', posts_path, class: 'btn btn-primary btn-lg rounded center' %>
  </div>
</div>

app/views/resume/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
<script defer src="https://use.fontawesome.com/releases/v5.1.1/js/all.js" integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a" crossorigin="anonymous"></script>
<article class="resume-wrapper text-center position-relative container">
  <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
    <header class="resume-header pt-md-0 web">
	    <div class="media flex-column flex-md-row">
		    <%= image_tag "jonathan6s.jpg", class: 'col-sm-3 img-fluid picture plr-0 mobile-resize' %>
		    <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
			    <div class="primary-info col-sm-6">
				    <h1 class="name mt-0 mb1 text-white text-uppercase text-uppercase">Jonathan Weyermann</h1>
				    <div class="title mb-3">Full Stack Developer</div>
				    <ul class="list-unstyled">
					    <li class="mb-2"><a href="#"><i class="far fa-envelope fa-fw mr-2" data-fa-transform="grow-3"></i>weyermannx@gmail.com</a></li>
					    <li><a href="#"><i class="fas fa-mobile-alt fa-fw mr-2" data-fa-transform="grow-6"></i>587 983 4845</a></li>
				    </ul>
			    </div><!--//primary-info-->
			    <div class="secondary-info col-sm-6 mt-2">
				    <ul class="resume-social list-unstyled">
		                <li class="mb-3"><a href="https://www.linkedin.com/in/jonathanweyermann/"><span class="fa-container text-center mr-2"><i class="fab fa-linkedin-in fa-2x fa-fw"></i></span>linkedin.com/in/jonathanweyermann/</a></li>
		                <li class="mb-3"><a href="https://www.github.com/jonathanweyermann"><span class="fa-container text-center mr-2"><i class="fab fa-github-alt fa-2x fa-fw"></i></span>github.com/jonathanweyermann</a></li>
		                <li><a href="http://www.jonathanweyermann.com"><span class="fa-container text-center mr-2"><i class="fas fa-2x fa-globe"></i></span>jonathanweyermann.com</a></li>
				    </ul>
			    </div><!--//secondary-info-->

		    </div><!--//media-body-->
	    </div><!--//media-->
    </header>
    <%= render partial: 'resume_body' %>


  </div>
</article>

<div class="center mt1">
  <%= link_to 'Download PDF Resume', '/resume_print.pdf', class: 'btn btn-primary btn-lg center' %>
</div>

app/views/resume/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
<script defer src="https://use.fontawesome.com/releases/v5.1.1/js/all.js" integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a" crossorigin="anonymous"></script>
<article class="resume-wrapper text-center position-relative container">
  <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
    <header class="resume-header pt-md-0 print">
	    <div class="media flex-column flex-md-row">
		    <div class="media-body p-2 d-flex flex-column flex-md-row mx-auto mx-lg-0">
			    <div class="primary-info col-xs-6">
				    <h1 class="name mt-2 mb1 text-white text-uppercase text-uppercase">Jonathan Weyermann</h1>
				    <div class="title mb-3">Full Stack Developer</div>
				    <ul class="list-unstyled">
					    <li class="mb-2"><a href="#"><i class="far fa-envelope fa-fw mr-2" data-fa-transform="grow-1"></i>weyermannx@gmail.com</a></li>
					    <li class="mb-2"><a href="#"><i class="fas fa-phone fa-fw mr-2" data-fa-transform="grow-1"></i>(587) 983-4845</a></li>
				    </ul>
			    </div><!--//primary-info-->
			    <div class="secondary-info col-xs-6 mt-2">
				    <ul class="resume-social list-unstyled">
                <li class="mb-3"><span class="fa-container text-center mr-2"><i class="fas fa-map-marker-alt fa-2x fa-fw"></i></span>10981 74th AVE NW, T6G 0E5, Edmonton, Alberta</li>
                <li class="mb-3"><a><span class="fa-container text-center mr-2"><i class="fab fa-linkedin-in fa-2x fa-fw"></i></span>linkedin.com/in/jonathanweyermann/</a></li>
                <li class="mb-3"><a><span class="fa-container text-center mr-2"><i class="fab fa-github-alt fa-2x fa-fw"></i></span>github.com/jonathanweyermann</a></li>
                <li><a><span class="fa-container text-center mr-2"><i class="fas fa-2x fa-globe"></i></span>www.jonathanweyermann.com</a></li>
				    </ul>
			    </div><!--//secondary-info-->

		    </div><!--//media-body-->
	    </div><!--//media-->
    </header>
    <%= render partial: 'resume_body' %>


  </div>
</article>