config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'admin/users', sessions: 'users/sessions' }
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'resume' => 'resume#index'
  get 'resume_print' => 'resume#show'


  namespace :admin do
  get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
  get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories
  resources :portfolios do
    resources :portfolio_chunks
  end
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :categories, :users, :sessions
    resources :portfolios do
      resources :portfolio_chunks
    end
    resources :posts do
      resources :comments
      resources :post_chunks
    end
  end

  resources :posts do
    resources :comments
  end

  root 'dashboard#index'

  post 'wysiwygs', to: "admin/wysiwyg#create"
  get 'wysiwygs', to: "admin/wysiwyg#index"
  delete 'wysiwyg/:id', to: "admin/wysiwyg#destroy"
end

app/models/category.rb
class Category < ActiveRecord::Base
	extend PagedSearchable

	has_many :posts

	validates :name, presence: true

	def self.search(quote)
		where("name like ?", "%#{query}%")
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	attr_accessor :user_name

	validate :no_robots
	validates_presence_of :name, :body
	validates_email_format_of :email, :message => 'please enter a valid email'

	def sub_comments
	  Comment.where(reply_comment: id)
	end

	def no_robots
		if user_name!='name'
			errors.add(:base, "please don't change any hidden fields")
		end
	end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged
	has_many :portfolio_chunks

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	enum publish: [:not_published, :is_published]

  def visible?
		return true if is_published?
	end

	def self.sorted_public
		visible.priority
	end

	def self.visible
		Portfolio.where(id: (select { |p| p.visible? }).map(&:id))
	end

	def self.priority
		order('priority','created_at DESC')
	end
end

app/models/portfolio_chunk.rb
class PortfolioChunk < ActiveRecord::Base
	belongs_to :portfolio

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	extend PagedSearchable

  friendly_id :title, use: :slugged
	belongs_to :category
	belongs_to :user
	has_many :wysiwygs
	has_many :comments
	has_many :post_chunks

	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image,	storage: :s3

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search(query)
		where("title like ? OR body like?", "%#{query}%","%#{query}%")
	end

	enum state: [:draft, :production]

  def visible?
		return false unless production?
		return true if publish_date.blank?
		return true if publish_date < Time.zone.now
		false
	end

	def self.public(page)
		visible.pub_sorted.paginate(:per_page => 10, :page => page)
	end

	def self.visible
		Post.where(id: (select { |p| p.visible? }).map(&:id))
	end

	def self.pub_sorted
		order('job_priority','publish_date DESC NULLS LAST','created_at DESC')
	end

	def visible_published_date
		return publish_date unless publish_date.blank?
		created_at.to_time
	end

	def root_comments
		comments.where(reply_comment: nil)
	end
end

app/models/post_chunk.rb
class PostChunk < ActiveRecord::Base
	belongs_to :post

	has_attached_file :image,	storage: :s3,
	  styles: {
      thumb: "100x100",
      small: "400x400",
      medium: "1400x1400"
		}

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  extend PagedSearchable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true, on: :create
	validates :password, confirmation: true, on: :create

	def self.search(query)
		where("name like ? OR email like?", "%#{query}%","%#{query}%")
	end
end

app/models/wysiwyg.rb
class Wysiwyg < ActiveRecord::Base
  belongs_to :post
  mount_uploader :image, ImageUploader

  attr_accessor :filename
end

app/controllers/comments_controller.rb
class CommentsController < PostsController
  def create
    comment = post.comments.create(comment_params)
    if comment.valid? && comment.save
      flash[:notice] = 'Comment Added'
      session.delete(:comment)
      redirect_to post_path(post, anchor: 'comment')
    else
      session[:comment] = comment
      flash[:alert] = Array(comment.errors).to_sentence
      redirect_to new_post_comment_path(post, comment_id: params["comment"]["reply_comment"], anchor: 'comment')
    end
  end

  private

  def comment_params
  	params.require(:comment).permit(:name, :email, :body, :post_id, :reply_comment, :user_name)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  caches_page :show, :index
  expose :post, find_by: :slug
  expose(:post_presenter) { post.decorate }
  expose(:posts_presenter) { PostsDecorator.decorate(posts_filter) }
  expose(:limited_posts) { Post.public(params[:page]).limit(4) }
  expose(:limited_posts_presenter) { PostsDecorator.decorate(limited_posts) }
  expose(:user) { post.user }

  private

  def posts_filter
    params[:search] ? Post.search(params[:search]).public(params[:page]) : Post.public(params[:page])
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  caches_page :index, :show
  layout "plain", only: 'show'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment_descriptor
    if params[:comment_id].present?
      raw ("Replying to comment #{Comment.find(params[:comment_id]).try(:name)}<span class='comment_date'>#{Comment.find(params[:comment_id]).try(:created_at).to_time.strftime('%B %e %Y at %l:%M %p')}</span>")
    else
      "Add Comment"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wysiwyg_helper.rb
module WysiwygHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jonathan's Blog</title>
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script data-ad-client="ca-pub-4245954284311066" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  </head>
  <body>
	  <nav class="navbar admin-navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><h1>Blog Manager</h1></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'admin/portfolios' ? 'active' : '' %>"><%= link_to 'Portfolio Pieces', admin_portfolios_path%></li>
            <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to 'Posts', admin_posts_path%></li>
            <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to 'Categories', admin_categories_path%></li>
            <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to 'Users', admin_users_path%></li>
    	    </ul>
          <%= render 'partials/admin/search' %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	  <div class="content well">
      <div id="user_nav" class="pull-right">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "log in", admin_login_path %>
        <% end %>
     </div>
     <!-- Alerts and Messages -->
     <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
     <% end %>
    <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
     <% end %>
	   <%= yield %>
    </div>
    <footer>
      <%= render 'partials/admin/footer'%>
    </footer>

</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Login | rBlog</title>
    <%= stylesheet_link_tag    'admin/login', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="container">

      <%= yield %>

    </div>
    <footer>
      <div class="container">
         <%= render 'partials/admin/footer' %>
      </div>
    </footer>
  </body>
</html>

app/views/partials/admin/_footer.html.erb
<p>Copyright &copy; 2019, Jonathan Weyermann | <%= link_to "Frontend", root_path, target:'_blank' %></p>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
	<%= form_tag(admin_posts_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
		<div class="form-group">
		  <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control' %>
		</div>
		<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
	<% end %>
<% elsif params[:controller] == 'admin/categories' %>
	<%= form_tag(admin_categories_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
		<div class="form-group">
		  <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class:'form-control' %>
		</div>
		<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
	<% end %>
<% elsif params[:controller] == 'admin/users' %>
	<%= form_tag(admin_users_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
		<div class="form-group">
		  <%= text_field_tag :search, params[:search], placeholder: "Search Users", class:'form-control' %>
		</div>
		<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
	<% end %>
<% end %>